Upgrade vulnerable deps: superagent & mocha
w3c/node-w3capi pull request #33
Opened 2018-08-10 21:32 UTC by BigBlueHat

Scary stuff, code. 😁 

Tests still pass, fwiw. 😉

2018-08-10 21:35 UTC, BigBlueHat commented
I've also added the `package-lock.json` file [as recommended by npm](https://docs.npmjs.com/files/package-lock.json).

Cheers!
🎩

2018-12-10 14:45 UTC, tripu commented
Tests on the main branch don't pass now (but not because of this PR).
Waiting to get #34 merged before reviewing this one.

2018-12-10 15:36 UTC, tripu requested changes
Thank you, @BigBlueHat!

* Do you mind rebasing against `origin/gh-pages`? I just fixed a recent error there, and tests on this branch won't pass now otherwise.
* We prefer exact versions; ie, no caret (see my suggestions).
* If we update all dependencies to their latest versions, all 3 vulns reported by `npm audit` are fixed (see my suggestions).
* I already confirmed that tests pass with these suggested changes, and that at least one dependent project ([Unitas](https://github.com/w3c/Unitas/)) works fine with these changes, too.

2018-12-10 15:36 UTC, tripu commented on package.json
>      "async": "2.1.4",
```suggestion
    "async": "2.6.1",
```

2018-12-10 15:36 UTC, tripu commented on package.json
> +    "superagent": "^3.8.3"
```suggestion
    "superagent": "4.0.0"
```

2018-12-10 15:36 UTC, tripu commented on package.json
>      "browserify": "14.0.0",
```suggestion
    "browserify": "16.2.3",
```

2018-12-10 15:36 UTC, tripu commented on package.json
> +    "mocha": "^5.2.0"
```suggestion
    "mocha": "5.2.0"
```

2019-01-18 08:20 UTC, merged

2019-01-18 08:30 UTC, tripu commented
@BigBlueHat, I merged your PR as it was, and then applied my suggestions: https://github.com/w3c/node-w3capi/commit/6288d46955c79eb376c4a0fb0aa60d3e82fc3141
Those solve one vulnerability alert. The build is [clean now](https://github.com/w3c/node-w3capi/network/alerts).